version: "3.3"

services:

  traefik:
    image: "traefik:v2.7.0"
    container_name: "traefik"
    restart: "always"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.letsencrypt.acme.email=letsencrypt@questionable.site"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--pilot.dashboard=false"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"

  landing:
    build: ./landing
    container_name: landing
    restart: always
    init: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=Host(`questionable.site`, `www.questionable.site`)"
      - "traefik.http.routers.landing.entrypoints=https"
      - "traefik.http.routers.landing.tls.certresolver=letsencrypt"

  links:
    build: ./links
    container_name: links
    restart: always
    command:
      - "-db"
      - "/db/links"
      - "-seed"
      - "${LINKS_SEED}"
      - "-url"
      - "https://questionable.site/link/"
      - "-v"
    volumes:
      - links:/db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.links.rule=Host(`questionable.site`, `www.questionable.site`) && PathPrefix(`/link`)"
      - "traefik.http.routers.links.entrypoints=https"
      - "traefik.http.routers.links.tls.certresolver=letsencrypt"
      - "traefik.http.routers.links.middlewares=links-stripprefix@docker"
      - "traefik.http.middlewares.links-stripprefix.stripprefix.prefixes=/link"

  install:
    build: ./install
    container_name: install
    restart: always
    environment:
      USER: the-maldridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.install.rule=Host(`questionable.site`, `www.questionable.site`) && PathPrefix(`/install`)"
      - "traefik.http.routers.install.entrypoints=https"
      - "traefik.http.routers.install.tls.certresolver=letsencrypt"
      - "traefik.http.routers.install.middlewares=install-stripprefix@docker"
      - "traefik.http.middlewares.install-stripprefix.stripprefix.prefixes=/install"

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always

  flashpaper:
    image: ghcr.io/the-maldridge/flashpaper:v0.1.2
    container_name: flashpaper
    restart: always
    environment:
      FLASHPAPER_BASEPATH: /flashpaper
      REDIS_ADDR: redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flashpaper.rule=Host(`questionable.site`, `www.questionable.site`) && PathPrefix(`/flashpaper`)"
      - "traefik.http.routers.flashpaper.entrypoints=https"
      - "traefik.http.routers.flashpaper.tls.certresolver=letsencrypt"

volumes:
  letsencrypt:
  links:
